### ISSUE TITLE
Feature Request: Set Expiration Date

### ISSUE THREAD

**Issue by Rouffy** [guillaumev/owncloud_for_filelink#28] opened 2015-06-29 16:19 UTC
Hello, nice addon!
My feature Request is:
I would like to set an expiration date for the sharing links generated from this addon.
I know there is a function in owncloud to set all sharing links with an expiration date, but thats not really what i'm looking for.

A little note in the mail text should also be given to the receiver of the mail.
Thanks ;-)

**Comment by godfuture** [comment] 2016-03-31 15:46
I want too, absolutely!

1+

**Comment by guillaumev** [comment] 2017-03-29 10:53
Closing as a duplicate of #6

**Closed by guillaumev** 2017-03-29 10:53 UTC
