### ISSUE TITLE
can't use self signed certificate

### ISSUE THREAD

**Issue by Jibec** [guillaumev/owncloud_for_filelink#29] opened 2015-07-15 16:15 UTC
Hi,

I'm using a self signed certificate, can you please do something ?

Horodatage : 15/07/2015 18:11:04
Erreur : ...r:443 utilise un certificat de sécurité invalide.
Le certificat n'est pas sûr car l'autorité délivrant le certificat est inconnue.
(Code d'erreur : sec_error_unknown_issuer)

thanks for this great plugin idea, i'll be please to help

**Comment by Jibec** [comment] 2015-07-15 16:16
may also be linked to that error : 
Horodatage : 15/07/2015 18:10:43
Erreur : [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getCharPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource:///modules/cloudFileAccounts.js :: cloudFileAccounts.getDisplayName :: line 207"  data: no]
Fichier Source : resource:///modules/cloudFileAccounts.js
Ligne : 211

**Comment by srsbiz** [comment] 2015-07-16 08:12
Duplicate of #8

**Closed** 2017-03-29 10:46 UTC
