### ISSUE TITLE
General Error on setup account

### ISSUE THREAD

**Issue by Matthias84** [guillaumev/owncloud_for_filelink#18] opened 2015-02-20 08:19 UTC
Hi,
this extension looks pretty interesting, but unfortunatly I can't make any progress on setting it up for my own OC instance. I know this looks like a support request, but as others might have same problems due to the to general "an error occured" message, I like to encourage that you add more specific messages to make it easier to analyze the problem :)

So I tried to connect via:
`
server-url https://www.mydomain/owncloud/
username myuser
password mypass
remotepath /
`
I also tried also without https (I'm on a shared hoster and use the main cert issued just for the host) and the (original) hostname. Also I tried different remotepaths, but nothing worked :-/

**Comment by horstk** [comment] 2015-02-21 15:49
I have the same problem. Older thunderbird versions worked quite good with this addon, but after updating thunderbird the addon refused to work, I currently work with thunderbird 31.4.0 and owncloud 7.0.4

**Comment by mdocken** [comment] 2015-02-22 16:37
What other addons do you have installed?  It's been my experience that conflicts between addons can arise after a TB upgrade.  

Just a thought!

Mark

On February 21, 2015 10:49:25 AM EST, horstk <notifications@github.com> wrote:
>I have the same problem. Older thunderbird versions worked quite good
>with this addon, but after updating thunderbird the addon refused to
>work, I currently work with thunderbird 31.4.0 and owncloud 7.0.4
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/guillaumev/owncloud_for_filelink/issues/18#issuecomment-75377372

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Matthias84** [comment] 2015-02-22 21:14
This is TB 31.4.0 on Linux Mint 17
with enabled addons:
* Enigmail 1.7.2
* Messaging Menue and Unity Launcher Integration 1.3.1
* OC for filelink 1.1

**Comment by guillaumev** [comment] 2015-03-23 14:50
Please try version 1.2: https://addons.mozilla.org/thunderbird/addon/owncloud-for-filelink/versions/

**Comment by tetsuo76** [comment] 2015-03-24 06:18
I am having the same problem with OC for filelink 1.2 on Linux Mint 17 & TB 31.5.0. (No other addons installed). btw it works great on Windows.

**Comment by Matthias84** [comment] 2015-03-24 06:39
Same here the 1.2 doesn't connect. Is there anything we can do to help you debugging?

**Comment by guillaumev** [comment] 2015-03-24 07:17
Just a thought: it seems like the pattern of the URL to your owncloud is https://www.yourdomain.com/owncloud/. @tetsuo76 and @Matthias84 Can you confirm this ? If it's the case, could you try setting the server URL to https://www.yourdomain.com/owncloud (without any trailing slash) and see what happens ?

**Comment by tetsuo76** [comment] 2015-03-24 13:55
@guillaumev Thanks for the quick response. My ownCloud URL is https://cloud.domain.com. I've tried both https://cloud.domain.com and https://cloud.domain.com/ and still get the same error.

**Comment by Matthias84** [comment] 2015-03-24 18:00
@guillaumev Sorry doesn't work for me, too I also checked both variants before and now. (indeed I already coded similar bugs ;))

If you send me an PM I can give you further details of my instance and if you like I add an user for testing purpose.

**Comment by guillaumev** [comment] 2015-03-25 07:32
@Matthias84 Yes please send me details of your instance with a test user at guillaume@viguierjust.com. Thanks.

**Comment by horstk** [comment] 2015-03-30 14:15
Same problem here. I  use owncloud 7.05 and owncloud_for_filelink 1.2, thunderbird 36.0.4
URL pattern is https://yourdomain.com/owncloud 

I get the following error in owncloud.log

{"app":"webdav","message":"Sabre\\DAV\\Exception\\NotImplemented: There was no handler found for this \"POST\" method","level":4,"time":"2015-03-30T14:13:35+00:00"}

Regards
Horst

**Comment by guillaumev** [comment] 2015-03-31 06:26
Hi,

After some debugging with @Matthias84, it seems like the issue comes from the owncloud installation, and not from the thunderbird extension. To find out whether your owncloud can work with the extension, go to:

[owncloud_base_url]/ocs/v1.php/apps/files_sharing/api/v1/shares

and use your username and password to login. You should see your shares in an XML format under "data". If you don't see them, then the extension won't work...

In the owncloud install of @Matthias84, the data element here was empty. Unfortunately, so far, we were not able to find out why this element was empty...

**Comment by srsbiz** [comment] 2015-03-31 12:38
I can reproduce empty **data** node when "Allow apps to use the Share API" is unchecked in admin panel

**Comment by tetsuo76** [comment] 2015-03-31 14:07
@guillaumev I was able to view all my shared folders using the URL you provided. I can give you access to my owncloud if that helps. Feel free to send me a pm. @srsbiz "Allow apps to use the Share API" was already checked. My ownCloud version is 8.0.2 (stable) and as I mentioned earlier I am trying the add-on on a Linux Mint 17 & Thunderbird 31.5.0.

**Comment by guillaumev** [comment] 2015-04-01 06:56
@tetsuo76 Feel free to send me details of your instance and a test user at guillaume@viguierjust.com. I will see what I can do, but I don't know exactly when...

**Comment by tetsuo76** [comment] 2015-04-08 07:56
This is for @Matthias84 and the rest of Linux users that had the same problem. I've managed to make it work! I was having a weird caching problem. Try deleting first any ownCloud saved passwords on Thunderbird/Preferences/Security/Passwords. Then login to your ownCloud and change your ownCloud user password to something simple (without any symbols etc that seems to be an issue as well) and try to connect with filelink again. Try entering your attachments directory in this format /Attachments/

**Comment by Blaimi** [comment] 2015-04-08 17:13
Deleting the passwords worked for me, too. Before I had 2 Passwords saved, the first one from the Canlendars and the other one from filelink. After deleting, I added the filelink-stuff and now the calendars also working—with only one password stored in the password-manager.

**Comment by Matthias84** [comment] 2015-04-11 14:13
@guillaumev Thanks for your support :-) I now switched to OC 8.02 and at least it works with http. Do you think it's worth to investigate if there are remaining problems with the CAcert setup?

**Comment by gfa** [comment] 2015-04-21 09:14
i have the same problem, i cannot configure the account, i don't see anything on server log neither on thunderbird's error console. if i use curl to connect to the url it works fine. i've added CAcert to the list of trusted CA on thunderbird. how can i get more debug to troubleshot?

**Comment by gfa** [comment] 2015-04-21 09:19
@tetsuo76 i had data empty node on the xml until i enabled share API **and** share a file

**Comment by yuniers** [comment] 2016-01-29 22:14
I'm experiment the same.
Please see [this comment](https://github.com/guillaumev/owncloud_for_filelink/issues/38#issuecomment-176992129)

**Comment by guillaumev** [comment] 2017-03-29 10:50
Closing this, please try version 1.4 and reopen if needed.

**Closed by guillaumev** 2017-03-29 10:50 UTC
